# Generated by Django 3.2.5 on 2021-07-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media/images/profile.png', upload_to='media/images/'),
        ),
    ]
